### ISSUE TITLE
frustrating way to learn

### ISSUE THREAD

**Issue by joshtho** [learn-co-curriculum/phase-0-pac-3-arithmetic-lab#4]
the lessons on canvas in this one and the last one doesn't give me enough information or walkthrough to know what it is im supposed to be doing in the test. For almost every one of these tests to pass I had to look on slack and see if it was explained there (luckily it was). Its very frustrating and time consuming and I feel like I'm just copying down what people are saying and not really learning anything. Some of the people on slack are giving solutions that I have no idea what they mean (I think they are just figuring out a different way to do it) but luckily I recognize that and try to find syntax that is in the lesson. it is just so incredibly frustrating that the lesson tells you what the syntax is very briefly and then just kind of leaves you to figure out how to pass the tests for yourself without even giving you a prompt of what the answer is supposed to look like. 
I feel like it would be way more beneficial if there were a video of someone showing a ballpark range of what it is we're supposed to type down and why. Especially when it comes to learning how to read the index-test.js as well. Im taking these courses to learn what everything means and execute it correctly but its hard to do that when I dont have a lot of info or examples on what it is im supposed to do, or how yall want me to write it.

**Comment by lizbur10** [comment]
Hi @joshtho ! Thanks for providing this feedback. We have updated the lab instructions to try to make them clearer. Please note that you may not see these changes reflected in your Canvas course, but you can view them here on GitHub.

Apologies for the frustrations you encountered, and thanks for contributing to the Flatiron School curriculum 💙
